### ISSUE TITLE
Cannot make links to form a tree

### ISSUE THREAD

**Issue by brady77** [bimlas/tw5-locator#3]
Hi,

I cannot figure out how to make a tree from the links as stated in [this article](https://bimlas.gitlab.io/tw5-locator/#README) (see "The links in the text also form a tree")

Did I miss something?

Thanks. Petr

**Comment by bimlas** [comment]
Hi,

First of all thanks for using the plugin!

Unfortunately, the documentation is not the best, it is cumbersome enough for me to write in a way that everyone can understand. You can read about navigating by links here ("Use links in text as table of contents"):

https://bimlas.gitlab.io/tw5-locator/#View%20items%20with%20different%20templates%2C%20mindmap%20features

**Comment by brady77** [comment]
Actually, I missed something important. I'm using the Stoll plugin (https://giffmex.org/stroll/stroll.html) that bings the Roam Research experince to TW - awesome functionality. The links that I see in my tiddlers are actually "backlins" from other tiddlers. Unfortunatelly, those are not taken into account when building the tree for your super cool plugin. Do you think it is possible add the backlinks to filters?

Thanks.

**Comment by bimlas** [comment]
To display a list of backlinks, use the "Invert direction" button in the settings (you can read about it in the same description under "Invert direction, find out where the tiddler is in the tree").

**Comment by brady77** [comment]
It may not make a sence, but I will try to ask, anyway... Is it possible to modify the plugin so it shows all the links regardless of the "direction"? What I'm trying to achieve is a universal filter that shows all the links of any depth to and from a given tiddler.

**Comment by bimlas** [comment]
Sorry for the late reply.

To view all outbound links recursivelly, you can use the "search in context" button while LINKS-IN-TEXT is specified in the settings. See: https://bimlas.gitlab.io/tw5-locator/#Walk-through -> Search in current context
Unfortunately, this feature does not work in the other way (backlinks).

As you would like to see all the links, this plugin does not provide a solution, sorry.
