### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by fkohrt** [bimlas/tw5-locator#7]
I'm excited to use the Locator plugin for a community wiki project; however I noticed that there's no license notice so far. Could you add a `LICENSE` file that allows others to use the Locator plugin? I guess MIT or the BSD 3-Clause would be great choices, the latter is also used by TiddlyWiki itself.

**Comment by bimlas** [comment]
Added MIT license to repo's root directory. Is this correct or do I need to add it to the plugin itself? If so, how? (sorry, but I haven't added license to TiddlyWiki plugin or seen an example of it yet)

**Comment by bimlas** [comment]
By the way, i think you should wait for the next release which is practically ready but the documentation is so bad that i don't want to release it until i have completely rewritten it. However, in the absence of my poor English knowledge (and enthusiasm), this is done slowly.

This would belong to another issue, but do you think the tutorials that contain the videos are pretty clear? Can you understand how the plugin works through them? Or are descriptions with a lot of text more useful? I find the plugin relatively easy to use, but it’s not clear to most users and so I don’t know how to show them how it works.

To see how the user interface has evolved, visit the https://bimlas.gitlab.io/ page.

**Comment by fkohrt** [comment]
> Is this correct or do I need to add it to the plugin itself?

This depends on the license choice, the MIT demands (see e.g. [here](https://choosealicense.com/licenses/mit/)) that everybody who redistributes the software includes the license text. Therefore it would be more convenient for reuse if you included the license text with the plugin.

> If so, how?

Mohammad includes a license tiddler to the plugin files (see e.g. for [Shiraz](https://kookma.github.io/TW-Shiraz/#%24%3A%2Fplugins%2Fkookma%2Fshiraz)).

Thank you already!

> do you think the tutorials that contain the videos are pretty clear?

When using software I tend to not look at the documentation until I deem it necessary. I had discovered your plugin soon after I discovered TiddlyWiki, but it took me a while to actually study what the plugin can do. The interface seemed not that self-revealing to me, but my curiosity eventually prevailed and I've done your walk-through.

> Can you understand how the plugin works through them?

I find the documentation unusually extensive, which is great once I began to read it. However I would start (only) with a concise list of solved problems and features (aka highlights) on the first page and then provide more text on subsequent tiddlers.

> Or are descriptions with a lot of text more useful?

Especially for this plugin I found the videos very helpful and wouldn't want to miss them; explaining user interfaces works better through image than through text in my opinion. The only thing, as explained, was that it took me quite long what _exactly_ it is the plugin can do before diving into it. But maybe that's just me.

To be specific, I would move [the first few sentences](https://github.com/bimlas/tw5-locator/blob/c4e59aa/tiddlers/README.tid#L7-L23) back, only provide a [short description](https://github.com/bimlas/tw5-locator/blob/c4e59aa/tiddlers/README.tid#L25) followed by a short video. Then maybe a bulleted list with the features that are currently [hidden](https://github.com/bimlas/tw5-locator/blob/ba1f5e4/tiddlers/View items with different templates%2C mindmap features.tid) and a little [wide spread](https://github.com/bimlas/tw5-locator/blob/27d5a8c/tiddlers/Locator%20search%20and%20fields%20tabs.tid). If you now have the attention of the gentle reader you can point him first to a walkthrough and then to the extensive documentation.

**Comment by bimlas** [comment]
Added license to the plugin itself. I will close the issue, but I have written down your suggestions for myself.
